version: "3"

volumes:
  static_files:
  uploaded_files:

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    volumes:
      - ./main:/main
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    env_file:
      - ./.envs/.web
      - ./.envs/.gunicorn
    depends_on:
      - node_0
      - node_1
    links:
      - node_0
      - node_1
    restart: unless-stopped

  node_0:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - "10042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=book_cluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_0
    links:
      - node_1

  node_1:
    image: cassandra:2.2.0
    restart: unless-stopped
    ports:
      - "11042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=book_cluster
      - CASSANDRA_SEEDS=node_0, node_1
      - CASSANDRA_LISTEN_ADDRESS=node_1

  nginx:
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    depends_on:
      - web
    container_name: recsys_nginx_3
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.8.3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
    hostname: rabbitmq
    restart: unless-stopped

  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: ["redis-server", "--protected-mode", "no"]
    hostname: redis
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    command: celery worker -A app.Utils.celeryUtils.celapp --loglevel=INFO
    env_file:
      - ./.envs/.web
    volumes:
      - ./main:/main
    depends_on:
      - rabbitmq
      - redis
    links:
      - rabbitmq
      - redis
    restart: unless-stopped
