version: '3'

volumes:
  db-data:
  static_files:
  uploaded_files:

services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/web/Dockerfile
    volumes:
      - ./main:/main
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    env_file:
      - ./.envs/.web
      - ./.envs/.gunicorn
    depends_on:
      - cassandra
    links:
      - cassandra
    # container_name: recsys_web_3
    restart: on-failure

  cassandra:
    image: cassandra:2.2.0
    volumes:
      - db-data:/var/lib/cassandra/data
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter
    hostname: cassandra
    container_name: recsys_cass_3
    restart: on-failure
  
  nginx:
    container_name: nginx:1.18.0-alpine
    build:
      context: .
      dockerfile: ./dockerfiles/nginx/Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - static_files:/static_files
      - uploaded_files:/uploaded_files
    depends_on:
      - web
    container_name: recsys_nginx_3
    restart: on-failure

  # rabbitmq:
  #   image: rabbitmq:3.8.3-management
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=mypass
  #   ports:
  #     - "5672:5672"
  #   hostname: rabbitmq
  #   container_name: recsys_rmq_2
  #   restart: on-failure

  # redis:
  #   image: redis:5.0.5
  #   ports:
  #     - "6379:6379"
  #   expose:
  #     - "6379"
  #   command: [ "redis-server", "--protected-mode", "no" ]
  #   hostname: redis
  #   container_name: recsys_redis_2
  #   restart: on-failure

  # celery:
  #   build:
  #     context: .
  #     dockerfile: ./dockerfiles/web/Dockerfile
  #   command: celery worker -A utils.celery_tasks.main_app --loglevel=INFO
  #   env_file:
  #     - ./.envs/.web
  #   volumes:
  #     - ./main:/main
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #     - redis
  #   links:
  #     - rabbitmq
  #     - redis
  #   container_name: recsys_celery_2
  #   restart: on-failure